-- ServdGo — the things worth waking up for.
--
-- An alert is generated, not raised by hand, and every generator carries a
-- dedupe_key so a condition that stays true for six hours produces one row, not
-- one row every fifteen minutes. Acknowledging closes it; the same condition
-- recurring later opens a new one, which is the behaviour you want — an alert
-- that can never re-fire is a silence you did not ask for.

create type alert_severity as enum ('info', 'warning', 'critical');

create table alerts (
  id              bigint generated always as identity primary key,
  territory_id    uuid references territories (id) on delete cascade,
  kind            text not null,
  severity        alert_severity not null default 'warning',
  title           text not null,
  detail          text,
  -- One open alert per key. Closing it lets the same condition alert again.
  dedupe_key      text not null,
  entity          text,
  entity_id       text,
  acknowledged_by uuid references profiles (id),
  acknowledged_at timestamptz,
  created_at      timestamptz not null default now()
);

create unique index alerts_open_dedupe on alerts (dedupe_key) where acknowledged_at is null;
create index alerts_open_idx on alerts (territory_id, created_at desc) where acknowledged_at is null;

comment on table alerts is
  'Generated by the sweep below. dedupe_key is unique among OPEN alerts, so a persisting condition does not spam.';

create or replace function raise_alert(
  p_kind text, p_dedupe text, p_title text,
  p_detail text default null, p_territory uuid default null,
  p_severity alert_severity default 'warning',
  p_entity text default null, p_entity_id text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  insert into alerts (territory_id, kind, severity, title, detail, dedupe_key, entity, entity_id)
  values (p_territory, p_kind, p_severity, p_title, p_detail, p_dedupe, p_entity, p_entity_id)
  on conflict (dedupe_key) where acknowledged_at is null do nothing
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function raise_alert(text, text, text, text, uuid, alert_severity, text, text) from public;
grant execute on function raise_alert(text, text, text, text, uuid, alert_severity, text, text) to service_role;

create or replace function acknowledge_alert(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare a alerts;
begin
  select * into a from alerts where id = p_id;
  if a.id is null then
    raise exception 'No such alert' using errcode = 'no_data_found';
  end if;
  if not (is_franchisor() or (is_staff() and a.territory_id = current_territory_id())) then
    raise exception 'That alert is not yours' using errcode = 'insufficient_privilege';
  end if;
  update alerts set acknowledged_by = auth.uid(), acknowledged_at = now()
   where id = p_id and acknowledged_at is null;
  perform log_action('alert.acknowledged', 'alert', p_id::text, a.territory_id,
                     jsonb_build_object('kind', a.kind, 'title', a.title));
end;
$$;
revoke all on function acknowledge_alert(bigint) from public;
grant execute on function acknowledge_alert(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- The generators.
--
-- Business hours are the city's own — a city in another timezone should not be
-- alerted for having no riders at what is 3am to them. 08:00–20:00 local is a
-- stand-in for the `schedule` column, which has no agreed shape yet.
-- ---------------------------------------------------------------------------
create or replace function generate_alerts()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  t       record;
  o       record;
  r       record;
  w       record;
  n       integer := 0;
  v_hour  int;
  v_day   text;
  v_limit numeric;
begin
  for t in select * from territories where status::text = 'live' loop
    v_hour := extract(hour from (now() at time zone coalesce(t.timezone, 'Asia/Manila')));
    v_day  := to_char((now() at time zone coalesce(t.timezone, 'Asia/Manila'))::date, 'YYYY-MM-DD');

    -- 1. Nobody online while the city is meant to be open.
    if t.is_open and v_hour between 8 and 19 then
      if not exists (select 1 from riders
                      where territory_id = t.id and is_online
                        and application_status = 'approved' and not is_suspended) then
        if raise_alert('no_riders_online',
             format('no_riders:%s:%s:%s', t.id, v_day, v_hour / 4),
             format('%s has no riders online', t.name),
             'The city is open and nobody is available to take an order.',
             t.id, 'critical', 'territory', t.id::text) is not null then
          n := n + 1;
        end if;
      end if;
    end if;

    -- 2. Scorecard breaches.
    declare b text[] := scorecard_breaches(t.id);
    begin
      if array_length(b, 1) > 0 then
        if raise_alert('scorecard_breach',
             format('scorecard:%s:%s', t.id, v_day),
             format('%s is breaching its thresholds', t.name),
             array_to_string(b, '; '), t.id, 'warning', 'territory', t.id::text) is not null then
          n := n + 1;
        end if;
      end if;
    end;

    -- 3. A rider carrying more float than the limit allows.
    v_limit := coalesce(t.cod_float_limit,
                        (select cod_float_limit from platform_settings where id = true), 3000);
    for r in
      select cl.rider_id, ri.name, sum(cl.amount) as owed
        from commission_ledger cl
        join riders ri on ri.id = cl.rider_id
       where cl.territory_id = t.id and not cl.settled
       group by 1, 2 having sum(cl.amount) > v_limit
    loop
      if raise_alert('cod_over_limit',
           format('cod:%s:%s', r.rider_id, v_day),
           format('%s is holding %s in unsettled commission', r.name, round(r.owed, 2)),
           format('Above the %s float limit for %s.', v_limit, t.name),
           t.id, 'warning', 'rider', r.rider_id::text) is not null then
        n := n + 1;
      end if;
    end loop;
  end loop;

  -- 4. An order nobody has taken. Ten minutes is long enough that it is not a
  --    blip and short enough that somebody can still act on it.
  for o in
    select id, territory_id, created_at from orders
     where status = 'pending' and rider_id is null
       and created_at < now() - interval '10 minutes'
       and created_at > now() - interval '1 day'
  loop
    if raise_alert('order_unassigned',
         format('unassigned:%s', o.id),
         'An order has been waiting for a rider',
         format('Placed %s minutes ago and still unassigned.',
                round(extract(epoch from (now() - o.created_at)) / 60)),
         o.territory_id, 'critical', 'order', o.id::text) is not null then
      n := n + 1;
    end if;
  end loop;

  -- 5. A partner's callbacks failing repeatedly.
  for w in
    select d.id, d.merchant_id, d.attempts, d.last_error, m.name, m.territory_id
      from merchant_webhook_deliveries d
      join merchants m on m.id = d.merchant_id
     where d.status = 'pending' and d.attempts >= 3
  loop
    if raise_alert('webhook_failing',
         format('webhook:%s', w.id),
         format('Callbacks to %s are failing', w.name),
         format('%s attempts, last error: %s', w.attempts, coalesce(w.last_error, 'none recorded')),
         w.territory_id, 'warning', 'merchant', w.merchant_id::text) is not null then
      n := n + 1;
    end if;
  end loop;

  return n;
end;
$$;
revoke all on function generate_alerts() from public;
grant execute on function generate_alerts() to service_role, authenticated;

grant select on alerts to authenticated;
grant all on alerts to service_role;
alter table alerts enable row level security;

create policy alerts_read on alerts
  for select using (is_franchisor() or (is_staff() and territory_id = current_territory_id()));

-- ---------------------------------------------------------------------------
-- Schedules. Same conditional shape as 0100 — pg_cron is not everywhere.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    raise notice 'pg_cron is not available here — the scorecard refresh and alert sweep are NOT scheduled.';
    return;
  end if;
  execute 'create extension if not exists pg_cron';

  begin perform cron.unschedule('servdgo-scorecard-refresh'); exception when others then null; end;
  begin perform cron.unschedule('servdgo-alert-sweep');       exception when others then null; end;

  perform cron.schedule('servdgo-scorecard-refresh', '*/15 * * * *',
                        'select public.refresh_scorecard();');
  perform cron.schedule('servdgo-alert-sweep', '*/15 * * * *',
                        'select public.generate_alerts();');
end $$;
