-- ServdGo — CSV exports, generated by the database rather than the browser.
--
-- The admin console already renders these tables; the reason to export them is
-- that somebody wants a year of them in a spreadsheet, which is exactly the
-- case where fetching them into the browser first falls over. So the rows are
-- turned into lines here and streamed out by the hq-export function.
--
-- Times come out in the city's own timezone, because the person reading the
-- spreadsheet is in that city. Money comes out as it is stored — two decimal
-- places, never a float.

/** One CSV cell, quoted only when it has to be. */
create or replace function csv_cell(p_value text)
returns text
language sql
immutable
as $$
  select case
    when p_value is null then ''
    when p_value ~ ('[",' || chr(10) || chr(13) || ']') then '"' || replace(p_value, '"', '""') || '"'
    else p_value
  end;
$$;

/** One CSV line, in the order the cells were given. */
create or replace function csv_line(p_cells text[])
returns text
language sql
immutable
as $$
  select string_agg(csv_cell(c), ',' order by n)
    from unnest(p_cells) with ordinality as u(c, n);
$$;

/**
 * A dataset for one city as CSV lines, header first.
 *
 * Returns lines rather than a single blob so the caller can stream it: a year
 * of deliveries is megabytes, and nobody needs it assembled in memory first.
 */
create or replace function hq_export(
  p_dataset   text,
  p_territory uuid,
  p_from      date default null,
  p_to        date default null
)
returns setof text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tz   text;
  v_from date := coalesce(p_from, current_date - 30);
  v_to   date := coalesce(p_to, current_date);
begin
  if p_territory is null then
    raise exception 'Export one city at a time' using errcode = 'check_violation';
  end if;
  if not staff_sees(p_territory) then
    raise exception 'not authorised' using errcode = 'insufficient_privilege';
  end if;
  if v_to < v_from then
    raise exception 'The end of the period is before its start' using errcode = 'check_violation';
  end if;

  select coalesce(timezone, 'Asia/Manila') into v_tz from territories where id = p_territory;
  if v_tz is null then
    raise exception 'No such territory' using errcode = 'no_data_found';
  end if;

  if p_dataset = 'deliveries' then
    return next csv_line(array['order_id','placed_at','delivered_at','status','service',
                               'rider','customer','contact','address','delivery_fee',
                               'store_fees','convenience_fee','goods','commission','payment']);
    return query
      select csv_line(array[
        o.id::text,
        to_char(o.created_at at time zone v_tz, 'YYYY-MM-DD HH24:MI'),
        to_char(o.delivered_at at time zone v_tz, 'YYYY-MM-DD HH24:MI'),
        o.status::text, o.service_type::text,
        r.name, o.customer_name, o.customer_contact, o.delivery_address,
        o.delivery_fee::text, o.store_fee_total::text, o.convenience_fee::text,
        o.goods_cost::text, o.commission_amount::text, o.payment_method::text])
        from orders o
        left join riders r on r.id = o.rider_id
       where o.territory_id = p_territory
         and (o.created_at at time zone v_tz)::date between v_from and v_to
       order by o.created_at;

  elsif p_dataset = 'commissions' then
    return next csv_line(array['ledger_id','business_day','rider','order_id','kind',
                               'amount','settled']);
    return query
      select csv_line(array[
        c.id::text, c.business_day::text, r.name, c.order_id::text, c.kind,
        c.amount::text, c.settled::text])
        from commission_ledger c
        join orders o on o.id = c.order_id
        left join riders r on r.id = c.rider_id
       where o.territory_id = p_territory
         and c.business_day between v_from and v_to
       order by c.business_day, r.name;

  elsif p_dataset = 'remittances' then
    return next csv_line(array['settlement_id','business_day','rider','amount_due',
                               'method','reference','status','confirmed_at']);
    return query
      select csv_line(array[
        s.id::text, s.business_day::text, r.name, s.amount_due::text,
        s.method, s.reference, s.status::text,
        to_char(s.confirmed_at at time zone v_tz, 'YYYY-MM-DD HH24:MI')])
        from settlements s
        join riders r on r.id = s.rider_id
       where r.territory_id = p_territory
         and s.business_day between v_from and v_to
       order by s.business_day, r.name;

  elsif p_dataset = 'royalty' then
    return next csv_line(array['entry_id','business_day','kind','base_amount','rate',
                               'amount','order_id','note']);
    return query
      select csv_line(array[
        y.id::text, y.business_day::text, y.kind, y.base_amount::text, y.rate::text,
        y.amount::text, y.order_id::text, y.note])
        from royalty_ledger y
       where y.territory_id = p_territory
         and y.business_day between v_from and v_to
       order by y.business_day;

  elsif p_dataset = 'invoices' then
    return next csv_line(array['invoice_id','period_start','period_end','amount_due',
                               'amount_settled','status','method','reference',
                               'issued_at','confirmed_at']);
    return query
      select csv_line(array[
        i.id::text, i.period_start::text, i.period_end::text, i.amount_due::text,
        i.amount_settled::text, i.status::text, i.method, i.reference,
        to_char(i.created_at at time zone v_tz, 'YYYY-MM-DD HH24:MI'),
        to_char(i.confirmed_at at time zone v_tz, 'YYYY-MM-DD HH24:MI')])
        from operator_settlements i
       where i.territory_id = p_territory
         and i.period_start <= v_to and i.period_end >= v_from
       order by i.period_start;

  else
    raise exception 'Unknown dataset %. Try deliveries, commissions, remittances, royalty or invoices.',
      p_dataset using errcode = 'check_violation';
  end if;

  perform log_action('hq.exported', 'export', p_dataset, p_territory,
                     jsonb_build_object('from', v_from, 'to', v_to));
end;
$$;
revoke all on function hq_export(text, uuid, date, date) from public;
grant execute on function hq_export(text, uuid, date, date) to authenticated;
